Repository citizenfx/natives, pull requests merged in 2024-08, with the labels that each got.

#1150 [GRAPHICS - SetDisablePetrolDecalsIgnitingThisFrame]: Resolved Name & Documented Native
  GRAPHICS/N_0xd9454b5752c857dc.md
  GRAPHICS/SetDisablePetrolDecalsIgnitingThisFrame.md
Labels: ready-to-merge

#1147 [ENTITY - DeleteEntity]: Updated C# example to resolve errors
  ENTITY/DeleteEntity.md
Labels: ready-to-merge

#1146 feat(docs/natives/RENDER_SCRIPT_CAMS): Renamed and explained the 4th …
  CAM/RenderScriptCams.md
Labels: ready-to-merge

#1144 Document UnrequestTennisBanks
  AUDIO/N_0x0150b6ff25a9e2e5.md
  AUDIO/UnrequestTennisBanks.md
Labels: ready-to-merge

#1142 Update SetIkTarget
  PED/SetIkTarget.md
Labels: ready-to-merge

#1135 Update flags for TaskPlayAnim
  TASK/TaskPlayAnim.md
  TASK/TaskPlayAnimAdvanced.md
Labels: ready-to-merge

#782 Attempt to fix empty docs for ToggleVehicleMod
  VEHICLE/ToggleVehicleMod.md
Labels: ready-to-merge

#1151 [PLAYER- GetIsPlayerDrivingOnHighway]: Resolved Name & Documented Native
  PLAYER/GetIsPlayerDrivingOnHighway.md
  PLAYER/N_0x5fc472c501ccadb3.md
Labels: ready-to-merge

#1137 Update SetFollowPedCamThisUpdate
  CAM/SetFollowPedCamThisUpdate.md
Labels: ready-to-merge

#1099 Use real names for remaining scaleform natives
  GRAPHICS/EndTextCommandScaleformString_2.md
  GRAPHICS/EndTextCommandUnparsedScaleformString.md
  GRAPHICS/GetScaleformMovieMethodReturnValueBool.md
  GRAPHICS/ScaleformMovieMethodAddParamLiteralString.md
  GRAPHICS/ScaleformMovieMethodAddParamTextureNameString_2.md
  GRAPHICS/SetScaleformFitRendertarget.md
  GRAPHICS/SetScaleformMovieToUseSuperLargeRt.md
Labels: ready-to-merge

#1054 document SET_WARNING_MESSAGE_WITH_HEADER_UNK
  HUD/SetWarningMessageWithHeaderExtended.md
  HUD/SetWarningMessageWithHeaderUnk.md
Labels: ready-to-merge

#948 Update TaskGoToCoordWhileAimingAtEntity.md
  TASK/TaskGoToCoordWhileAimingAtEntity.md
Labels: ready-to-merge

#943 Update TaskFollowPointRoute.md
  TASK/TaskFollowPointRoute.md
Labels: ready-to-merge

#942 Update TaskVehicleDriveToCoordLongrange.md
  TASK/TaskVehicleDriveToCoordLongrange.md
Labels: ready-to-merge

#905 Update GetGroundZFor_3dCoord.md
  MISC/GetGroundZFor_3dCoord.md
Labels: ready-to-merge

#795 Update CellCamMoveFinger.md
  MOBILE/CellCamMoveFinger.md
Labels: ready-to-merge

#783 Update GetGpsWaypointRouteEnd.md
  PATHFIND/GetGpsWaypointRouteEnd.md
  PATHFIND/GetPosAlongGpsTypeRoute.md
Labels: ready-to-merge

#1153 [ENTITY] Resolve names
  ENTITY/GetEntityHeadingFromEulers.md
  ENTITY/GetEntityPhysicsHeading.md
  ENTITY/N_0x694e00132f2823ed.md
  ENTITY/SetEntityRequiresMoreExpensiveRiverCheck.md
  ENTITY/SetWaitForCollisionsBeforeProbe.md
Labels: ready-to-merge

#1139 feat(natives/3258): add new natives for the 3258 gamebuild
  AUDIO/ForceVehicleEngineSynth.md
  CAM/ActivateCamWithInterpAndFovCurve.md
  CAM/InterpolateCamWithParams.md
  CUTSCENE/GetCutscenePlayTime.md
  OBJECT/SetObjectTargettableByPlayer.md
  PED/SetBlockAmbientPedsFromDroppingWeaponsThisFrame.md
  VEHICLE/GetIsVehicleElectric.md
  VEHICLE/GetVehicleDriveTrainType.md
Labels: ready-to-merge

#1130 tweak(docs/native): Update Task Native Enums & Params
  TASK/SetDriveTaskDrivingStyle.md
  TASK/TaskBoatMission.md
  TASK/TaskHeliMission.md
  TASK/TaskVehicleDriveToCoordLongrange.md
  TASK/TaskVehicleDriveWander.md
  TASK/TaskVehicleEscort.md
  TASK/TaskVehicleFollow.md
  TASK/TaskVehicleMission.md
  TASK/TaskVehicleMissionCoorsTarget.md
  TASK/TaskVehicleMissionPedTarget.md
  VEHICLE/SetPlaybackToUseAi.md
  VEHICLE/SetPlaybackToUseAiTryToRevertBackLater.md
  VEHICLE/StartPlaybackRecordedVehicleUsingAi.md
  VEHICLE/StartPlaybackRecordedVehicleWithFlags.md
Labels: needs validation, ready-to-merge

#1082 Update SetPedConfigFlag.md
  PED/SetPedConfigFlag.md
Labels: ready-to-merge

#1111 Document various text input box natives
  HUD/ForceCloseTextInputBox.md
  HUD/N_0x1185a8087587322c.md
  HUD/N_0x577599cced639ca2.md
  HUD/SetAllowCommaOnTextInput.md
  HUD/SetTextInputBoxEnabled.md
  MISC/CancelOnscreenKeyboard.md
  MISC/DisplayOnscreenKeyboard.md
  MISC/DisplayOnscreenKeyboardWithLongerInitialString.md
  MISC/NextOnscreenKeyboardResultWillDisplayUsingTheseFonts.md
  MISC/UpdateOnscreenKeyboard.md
Labels: ready-to-merge

#1157 Update documentation on some health related natives.
  ENTITY/SetEntityHealth.md
  PED/IsPedInjured.md
  PED/SetPedMaxHealth.md
Labels: ready-to-merge

#1156 tweak(natives/player): document that the recharge multiplier gets reset on player ped change
  PLAYER/SetPlayerHealthRechargeMultiplier.md
Labels: ready-to-merge

#1149 [PHYSICS - DoesRopeExist]: Added Native Documentation
  PHYSICS/DoesRopeExist.md
Labels: ready-to-merge

#1148 [PHYSICS - DeleteRope]: Added Native Documentation
  PHYSICS/DeleteRope.md
Labels: ready-to-merge

#1145 [PHYSICS - AddRope]: Updated Rope Type Info
  PHYSICS/AddRope.md
Labels: ready-to-merge

#1081 feat(natives/2545): introduce new natives from the 2545 gamebuild
  HUD/SetCustomMpHudColor.md
  HUD/ShowContactInstructionalButton.md
  MISC/IsJapaneseVersion.md
  MISC/IsSteamVersion.md
  TASK/TaskWarpPedDirectlyIntoCover.md
  VEHICLE/SetHeliResistToExplosion.md
Labels: ready-to-merge

#1076 feat(vehicles/roofs): updates vehicles roofs natives
  VEHICLE/DoesVehicleHaveRoof.md
  VEHICLE/IsVehicleAConvertible.md
  VEHICLE/LowerConvertibleRoof.md
  VEHICLE/RaiseConvertibleRoof.md
  VEHICLE/SetConvertibleRoof.md
  VEHICLE/SetConvertibleRoofLatchState.md
Labels: ready-to-merge

#1044 feat:Update docs for some cam natives and GetNetworkTime()
  CAM/AttachCamToPedBone_2.md
  CAM/CreateCamera.md
  CAM/CreateCameraWithParams.md
  CAM/HardAttachCamToEntity.md
  CAM/HardAttachCamToPedBone.md
  CAM/N_0x202a5ed9ce01d6e7.md
  CAM/N_0x271401846bd26e92.md
  CAM/UseScriptCamForAmbientPopulationOriginThisFrame.md
  NETWORK/GetNetworkTime.md
Labels: ready-to-merge

#899 fix: Flag for `StartShapeTestLosProbe`
  SHAPETEST/StartShapeTestLosProbe.md
Labels: ready-to-merge

#987 Document GetTattooShopDlcItemData
  FILES/GetTattooShopDlcItemData.md
Labels: ready-to-merge

#876 Update AddTextComponentSubstringKeyboardDisplay.md
  HUD/AddTextComponentSubstringKeyboardDisplay.md
Labels: ready-to-merge

#830 Add missing argument and improve documentation
  NETWORK/NetworkFadeInEntity.md
Labels: ready-to-merge

#1158 tweak(docs/vehicle): update plate indicies for b3095
  VEHICLE/GetVehicleNumberPlateTextIndex.md
  VEHICLE/SetVehicleNumberPlateTextIndex.md
Labels: ready-to-merge

#1102 feat(vehicle/3095): add/update nitrous natives
  VEHICLE/ClearNitrous.md
  VEHICLE/FullyChargeNitrous.md
  VEHICLE/GetRemainingNitrousDuration.md
  VEHICLE/IsNitrousActive.md
  VEHICLE/SetNitrousIsActive.md
  VEHICLE/SetOverrideNitrousLevel.md
  VEHICLE/SetVehicleNitroEnabled.md
  VEHICLE/SetVehicleUseHornButtonForNitrous.md
Labels: ready-to-merge

#1136 Update IsVehicleTyreBurst.md (indexes for 8 wheels)
  VEHICLE/IsVehicleTyreBurst.md
Labels: needs validation

#762 Updating node documentation
  PATHFIND/GetClosestRoad.md
  PATHFIND/GetNthClosestVehicleNodeWithHeading.md
  PATHFIND/GetVehicleNodeProperties.md
Labels: ready-to-merge

#1133 Update NetworkConcealPlayer.md
  NETWORK/NetworkConcealPlayer.md
Labels: needs validation

#1161 Update SetWeaponAnimationOverride.md
  WEAPON/SetWeaponAnimationOverride.md
Labels: needs validation

#1164 feat(natives/heli): update helicopters natives
  VEHICLE/GetHeliTailRotorHealth.md
  VEHICLE/SetDisableHeliExplodeFromBodyDamage.md
  VEHICLE/SetHeliTailBoomCanBreakOff.md
  VEHICLE/SetHeliTailExplodeThrowDashboard.md
Labels: ready-to-merge

#1166 tweak(natives/hud): add description and example for SET_BLIP_COLOUR
  HUD/SetBlipColour.md
Labels: ready-to-merge

#1163 feat(natives/object): add documentation for DELETE_OBJECT
  OBJECT/DeleteObject.md
Labels: ready-to-merge
